FROM nvidia/cuda:10.1-cudnn7-runtime-ubuntu18.04

MAINTAINER Carlos Gemmell

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    build-essential \
    git \
    software-properties-common

RUN add-apt-repository -y ppa:deadsnakes/ppa

RUN apt-get install -y python3 \
    python3-pip \
    python-setuptools

RUN pip3 install --force-reinstall --upgrade pip
RUN pip install tensorflow-gpu==2.0.0-rc1
RUN pip install torch torchvision
RUN pip install jupyter jupyterlab 
RUN pip install torchtext
