FROM nvidia/cuda:10.1-cudnn7-runtime-ubuntu18.04

MAINTAINER Carlos Gemmell

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    build-essential \
    git \
    wget vim \
    software-properties-common

RUN add-apt-repository -y ppa:deadsnakes/ppa

RUN apt-get install -y python3 \
    python3-pip \
    python-setuptools

RUN pip3 install --force-reinstall --upgrade pip
RUN pip install tensorflow-gpu==2.0.0-rc1 tensorflow_datasets
RUN pip install torch torchvision
RUN pip install jupyter jupyterlab tokenizer
RUN pip install torchtext pytorch-nlp nltk line_profiler

RUN apt-get install -y curl nodejs npm
RUN jupyter labextension install jupyterlab-drawio

RUN git config --global user.email "aquaktus@yahoo.co.uk"
RUN git config --global user.name "aquaktus"